version: '3'
services:
  node-red-mcp:
    image: nodered/node-red:4.0.0
    container_name: node-red-mcp
    ports:
      - "1899:1880"
    volumes:
      - ./node-red-docker/node_red_data:/data
    environment:
      ## Password: Not Allow run local
      ## You can change password in node-red-docker/settings.js file
      ## More info in https://nodered.org/docs/user-guide/runtime/securing-node-red
      ##ADMIN_PASSWORD: '7OhBgb4IcnJmxYJiZ73Fk.3Ht9qovXFmhVMncQ3WTT2Q9TO9WRgV6'
    depends_on:
      - mcp-host
    networks:
      - mcp-host-network

  mcp-host:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: mcp-host
    ports:
      - "3000:3000"
    networks:
      - mcp-host-network

networks:
  mcp-host-network:
    driver: bridge
